-- AlterTable
ALTER TABLE "criancas_adolescentes" ADD COLUMN     "Avaliacao_domicilio" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "Avaliacao_familiar" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "Avaliacao_individual" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "Escuta_especializada" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "Organ_cuidado_conjunto" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "Organ_cuidado_familia" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "Organ_cuidado_individual" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "agente_violador" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "data_encaminhamento" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "descricao_atendimento" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "motivacao_encaminhamento" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "motivacao_encaminhamento_outro" TEXT,
ADD COLUMN     "motivo_encerramento" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "motivo_encerramento_outro" TEXT,
ADD COLUMN     "orgao_responsavel" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "periodo_acompanhamento" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "relato_espontaneo" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "status" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "tipo_acompanhamento" TEXT NOT NULL DEFAULT '';
