-- AlterTable
ALTER TABLE "criancas_adolescentes" ALTER COLUMN "Avaliacao_domicilio" DROP NOT NULL,
ALTER COLUMN "Avaliacao_domicilio" DROP DEFAULT,
ALTER COLUMN "Avaliacao_domicilio" SET DATA TYPE TEXT,
ALTER COLUMN "Avaliacao_familiar" DROP NOT NULL,
ALTER COLUMN "Avaliacao_familiar" DROP DEFAULT,
ALTER COLUMN "Avaliacao_familiar" SET DATA TYPE TEXT,
ALTER COLUMN "Avaliacao_individual" DROP NOT NULL,
ALTER COLUMN "Avaliacao_individual" DROP DEFAULT,
ALTER COLUMN "Avaliacao_individual" SET DATA TYPE TEXT,
ALTER COLUMN "Escuta_especializada" DROP NOT NULL,
ALTER COLUMN "Escuta_especializada" DROP DEFAULT,
ALTER COLUMN "Escuta_especializada" SET DATA TYPE TEXT,
ALTER COLUMN "Organ_cuidado_conjunto" DROP NOT NULL,
ALTER COLUMN "Organ_cuidado_conjunto" DROP DEFAULT,
ALTER COLUMN "Organ_cuidado_conjunto" SET DATA TYPE TEXT,
ALTER COLUMN "Organ_cuidado_familia" DROP NOT NULL,
ALTER COLUMN "Organ_cuidado_familia" DROP DEFAULT,
ALTER COLUMN "Organ_cuidado_familia" SET DATA TYPE TEXT,
ALTER COLUMN "Organ_cuidado_individual" DROP NOT NULL,
ALTER COLUMN "Organ_cuidado_individual" DROP DEFAULT,
ALTER COLUMN "Organ_cuidado_individual" SET DATA TYPE TEXT;
